fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    wott\CoreBundle\Entity\User
    group:
        group_class: wott\CoreBundle\Entity\Group

fos_facebook:
    alias:  facebook
    app_id: %api_facebook_id%
    secret: %api_facebook_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]