# Services
services:

    wott.command.insertGenres:
        class: wott\CoreBundle\Command\InsertGenresCommand
        tags:
            -  { name: wott.insertGenres }
    wott.command.insertFilms:
        class: wott\CoreBundle\Command\InsertFilmsCommand
        tags:
            -  { name: wott.insertFilms }
    wott.command.insertPeoples:
        class: wott\CoreBundle\Command\InsertPeoplesCommand
        tags:
            -  { name: wott.insertPeoples }