sonata_user:
    manager_type: orm
    class:
        user:  wott\CoreBundle\Entity\User
        group: wott\CoreBundle\Entity\Group
    profile:
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.block.service.action:
        sonata.user.block.menu:
        sonata.user.block.account:

sonata_admin:
    title:      What's on TV tonight ?
    title_logo: bundles/wottback/img/logo.png
    templates:
        layout: "::standard_layout.html.twig"