<?php

namespace wott\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use wott\CoreBundle\Entity\User;

/**
 * FilmUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmUserRepository extends EntityRepository
{

    public function getLikesByUser(User $user)
    {
        $qb = $this->createQueryBuilder('fu');
        $query = $qb->select('fu, f')
                    ->join('fu.film', 'f')
                    ->where('fu.user = :user')
                    ->setParameter('user', $user)
                    ->getQuery();

        return $query->getResult();
    }

}
