<?php

namespace wott\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{

    public function getFilmsByPopularity($limit, $genre = null)
    {
        $qb = $this->createQueryBuilder('f');
        $query = $qb->orderBy('f.popularity', 'DESC');
        /*if($genre){
        	$query->where('f.genre', ':genre');
        	$query->setParameter('genre',$genre);
        }*/
        $query->setMaxResults($limit)->getQuery();

        return $query->getResult();
    }

}
