<?php

namespace wott\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use wott\CoreBundle\Entity\User;

/**
 * FilmUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmUserRepository extends EntityRepository
{
    public function getLikesByUser(User $User)
    {
        $qb = $this->createQueryBuilder('fu');
        $qb->select('fu, f')
                ->join('fu.film', 'f')
                ->where('fu.isLike = true AND fu.user = :user')
                ->setParameter('user', $User);

        return $qb->getQuery()->getResult();
    }

}
