<?php

namespace wott\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use wott\CoreBundle\Entity\Film;

/**
 * FilmPeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmPeopleRepository extends EntityRepository
{

    public function getCrewFilm(Film $film)
    {
        $qb = $this->createQueryBuilder('fp');
        $qb->select('fp, p')
                ->join('fp.people', 'p')
                ->where('fp.film = :film')
                ->setParameter('film', $film);

        return $qb->getQuery()->getResult();
    }

}
